<?php
session_start();
include ("dbconn.php");
include ("dbconn3.php");

function round_up($number, $precision = 2)
{
    $fig = (int) str_pad('1', $precision, '0');
    return (ceil($number * $fig) / $fig);
}

///Get Branch Information
$query = "SELECT * FROM branch where id=1"; //You don't need a ; like you do in SQL
$result = mysql_query($query);
$branchrow = mysql_fetch_array($result);
$connection;

echo mysql_error($connection);

//Get Document Header Information
$reporttype=$_REQUEST[''];


switch ($reporttype)
{
	
	case 'Daily':
	viewDailyReport();
	break;
	case 'Weekly':
	viewWeeklyReport();
	break;
	case 'Monthly':
	viewMonthlyReport();
	break;
	default:
	viewCustomReport();
		
}

function viewDailyReport()
{
	
echo $salesrep=$_REQUEST['docno'];

echo $username=$_REQUEST[];

echo $fromdate=$_REQUEST[''];

echo $dailydate=$_REQUEST[''];

//Get New Opportunities
$query2 = "SELECT * FROM opportunity where sales_rep='$salesrep' and DateInitiated='$dailydate'"; //You don't need a ; like you do in SQL
$result2 = mysql_query($query2);
$newopportunitiesrow = mysql_fetch_array($result2);
$connection;

echo mysql_error($connection);

//Get Open Opportunities
$query2 = "SELECT * FROM opportunity where sales_rep='$salesrep' and Status='Open'"; //You don't need a ; like you do in SQL
$result2 = mysql_query($query2);
$opportunitiesrow = mysql_fetch_array($result2);
$connection;

echo mysql_error($connection);

//Get Generated  Proformas
$query2 = "SELECT * FROM invserialsheader where sales_rep='$salesrep' and DDate='$dailydate'"; //You don't need a ; like you do in SQL
$result2 = mysql_query($query2);
$proformasrow = mysql_fetch_array($result2);
$connection;

echo mysql_error($connection)


//Get Lost Opportunities
$query2 = "SELECT * FROM opportunity where sales_rep='$salesrep' and Status='Cancelled' and DateCancelled='$dailydate' "; //You don't need a ; like you do in SQL
$result2 = mysql_query($query2);
$lostopportunitiesrow = mysql_fetch_array($result2);
$connection;

echo mysql_error($connection)

}

//Get Document Lines Information


$query3 = "SELECT * FROM invserialslines where docno='$profno'"; //You don't need a ; like you do in SQL
$result3 = mysql_query($query3);
//$headerrow = mysql_fetch_array($result2);
$connection;

echo mysql_error($connection);

$theNo=$headerrow['MonthlyRental']/1.15; 
$theVAT=$headerrow['MonthlyRental']-$theNo;


?>

<!DOCTYPE html>
<head>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<style>
.invoice-title h2, .invoice-title h3 {
    display: inline-block;
}

#proformaInvoiceTable > tbody > tr > .no-line {
    border-top: none;
}

#proformaInvoiceTable > thead > tr > .no-line {
    border-bottom: none;
}

#proformaInvoiceTable > tbody > tr > .thick-line {
    border-top: 2px solid;
}
@page {
    size: 25cm 35.7cm;
    margin: 5mm 5mm 5mm 5mm; /* change the margins as you want them to be. */
}
</style>

<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <div class="row">
        <div class="col-xs-12">
    		<div class="invoice-title">
    		<img src="http://qrent.co.zw/wp-content/uploads/2016/05/Qrent-Logo-75x.jpg">     <h2>Individual Sales Report</h2><h4 class="pull-right"> For:<?php echo $headerrow['reportuser']; ?></h2>
    		</div>
    		<hr>
    		<div class="row">
    			
    		<div class="row">
    			<div class="col-xs-6">
    				<address>
					<strong>Report Type:</strong>
    					<?php echo $reporttype; ?><br>
    					<strong>Generated By:</strong>
    					<?php echo $SESSION_['username']; ?><br>
    				<strong>Date Generated :</strong>
    					<?php echo date("d/m/Y"); ?><br>
    				
    				</address>
    			</div>
				</div>    			
    		<div class="row">
    			<div class="col-xs-6">
    				<address>
					<strong>SUMMARY:</strong><br>
    					<strong>Laptops Hired:</strong>
    					<?php echo $SESSION_['username']; ?><br>
    				<strong>Desktops Hired :</strong>
    					<?php echo date("d/m/Y"); ?><br>
    				<strong>Projectors Hired:</strong>
    					<?php echo date("d/m/Y"); ?><br>
							<strong>Servers Hired:</strong>
    					<?php echo date("d/m/Y"); ?><br>
    				<strong>Other Units:</strong>
    					<?php echo date("d/m/Y"); ?><br>
    				<strong>Revenue :</strong>
    					<?php echo date("d/m/Y"); ?><br>
    				
    				</address>
    			</div>
    			<div class="col-xs-6 text-right">
    				<address>
    					<strong>Report Period:</strong><br>
    				From: <?php $ddate=date_create($headerrow['StartDate']); echo	date_format($ddate,"d/m/Y "); ?><br>
					To: <?php $ddate=date_create($headerrow['EndDate']); echo	date_format($ddate,"d/m/Y "); ?><br>
					<br>
    				</address>
    			</div>
    		</div>
    	</div>
    </div>
    
    <div class="row">
    	<div class="col-md-12">
    		<div class="panel panel-default">
    			<div class="panel-heading">
    				<h3 class="panel-title"><strong>Opportunities & Leads</strong></h3>
    			</div>
    			<div class="panel-body">
    				<div class="table-responsive">
    					<table id="proformaInvoiceTable1" class="table table-condensed">
    						<thead>
                                <tr>
        							<td><strong>Item Description</strong></td>
        							<td class="text-center"><strong>Stage/Outcome</strong></td>
        							<td class="text-center"><strong>Maturity Date</strong></td>
        							<td class="text-right"><strong></strong></td>
                                </tr>
    						</thead>
    						<tbody>
							<?php
							while($row = mysql_fetch_array($result3)){   //Creates a loop to loop through results
		echo "<tr><td>".$row['StoreCode']." ".$row['Description']."</td><td class=\"text-center\">$ ".round_up($row['UnitCost'])."</td><td class=\"text-center\">".$row['Qty']."</td><td class=\"text-right\">$ ".round_up($row['LnTotal'])."</td></tr>";  //$row['index'] the index here is a field name
}
							?>
    							<!-- foreach ($order->lineItems as $line) or some such thing here -->
    							
    							
									<tr>
    								<td class="no-line"></td>
    								<td class="no-line"></td>
    								<td class="no-line text-center"><strong>Deposit Period</strong></td>
    								<td class="no-line text-right"><?php echo$headerrow['DepositPeriod']; ?> Months</td>
    							</tr>
								<tr>
    								<td class="no-line"></td>
    								<td class="no-line"></td>
    								<td class="no-line text-center"><strong>Deposit Amount</strong></td>
    								<td class="no-line text-right">$ <?php echo round_up($headerrow['DepositCash']); ?> </td>
    							</tr>
									<tr>
    								<td class="no-line"></td>
    								<td class="no-line"></td>
    								<td class="no-line text-center"><strong>Discount Amount</strong></td>
    								<td class="no-line text-right">$ <?php echo round_up($headerrow['Discount']); ?> </td>
    							</tr>
								<tr>
    								<td class="thick-line"></td>
    								<td class="thick-line"></td>
    								<td class="thick-line text-center"><strong>Subtotal</strong></td>
    								<td class="thick-line text-right">$ <?php echo round_up($headerrow['subtotal']); ?></td>
    							</tr>
    							<tr>
    								<td class="no-line"></td>
    								<td class="no-line"></td>
    								<td class="no-line text-center"><strong>Tax</strong></td>
    								<td class="no-line text-right">$ <?php echo round_up($headerrow['Tax']); ?></td>
    							</tr>
    							<tr>
    								<td class="no-line"></td>
    								<td class="no-line"></td>
    								<td class="no-line text-center"><strong>Total Due</strong></td>
    								<td class="no-line text-right">$ <?php echo round_up($headerrow['Total']); ?></td>
    							</tr>
    						</tbody>
    					</table>
						
    				</div>
					<div>
					
					</div>
    			</div>
				
				
				
				<div class="panel-body">
    				<div class="table-responsive">
    					<table id="proformaInvoiceTable1" class="table table-condensed">
    						<thead>
                                <tr>
        							<td><strong>Item Description</strong></td>
        							<td class="text-center"><strong>Stage/Outcome</strong></td>
        							<td class="text-center"><strong>Maturity Date</strong></td>
        							<td class="text-right"><strong></strong></td>
                                </tr>
    						</thead>
    						<tbody>
							<?php
							while($row = mysql_fetch_array($result3)){   //Creates a loop to loop through results
		echo "<tr><td>".$row['StoreCode']." ".$row['Description']."</td><td class=\"text-center\">$ ".round_up($row['UnitCost'])."</td><td class=\"text-center\">".$row['Qty']."</td><td class=\"text-right\">$ ".round_up($row['LnTotal'])."</td></tr>";  //$row['index'] the index here is a field name
}
							?>
    							<!-- foreach ($order->lineItems as $line) or some such thing here -->
    							
    							
									<tr>
    								<td class="no-line"></td>
    								<td class="no-line"></td>
    								<td class="no-line text-center"><strong>Deposit Period</strong></td>
    								<td class="no-line text-right"><?php echo$headerrow['DepositPeriod']; ?> Months</td>
    							</tr>
								<tr>
    								<td class="no-line"></td>
    								<td class="no-line"></td>
    								<td class="no-line text-center"><strong>Deposit Amount</strong></td>
    								<td class="no-line text-right">$ <?php echo round_up($headerrow['DepositCash']); ?> </td>
    							</tr>
									<tr>
    								<td class="no-line"></td>
    								<td class="no-line"></td>
    								<td class="no-line text-center"><strong>Discount Amount</strong></td>
    								<td class="no-line text-right">$ <?php echo round_up($headerrow['Discount']); ?> </td>
    							</tr>
								<tr>
    								<td class="thick-line"></td>
    								<td class="thick-line"></td>
    								<td class="thick-line text-center"><strong>Subtotal</strong></td>
    								<td class="thick-line text-right">$ <?php echo round_up($headerrow['subtotal']); ?></td>
    							</tr>
    							<tr>
    								<td class="no-line"></td>
    								<td class="no-line"></td>
    								<td class="no-line text-center"><strong>Tax</strong></td>
    								<td class="no-line text-right">$ <?php echo round_up($headerrow['Tax']); ?></td>
    							</tr>
    							<tr>
    								<td class="no-line"></td>
    								<td class="no-line"></td>
    								<td class="no-line text-center"><strong>Total Due</strong></td>
    								<td class="no-line text-right">$ <?php echo round_up($headerrow['Total']); ?></td>
    							</tr>
    						</tbody>
    					</table>
						
    				</div>
					<div>
					
					</div>
    			</div>
				
				
				
				
				
				
				
				
				
				
				
				
				
				
				
				
    		</div>
			
    	</div>
    </div>
	<div class="row">
    			<div class="col-xs-6">
				<strong>Remarks</strong><br>
				<?php echo $headerrow['Remarks']; ?>
				</div>
				</div>
				<div class="pull-right hidden-print">        
        <button class="btn btn-danger" onclick="window.print();">Print & Save Document</button>
        <button class="btn btn-danger" onclick="window.open('documents.php');">Back To Documents Menu</button>
    </div>    
</div>
</div>
<html>